### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by Vitalitypi** [ZhuoLinLi-shu/TPGCN#1]
您好，我看到您的论文已被接收，请问什么时候公开代码呢？

**Comment by ZhuoLinLi-shu** [comment]
3月15号之前吧。最近身体欠佳，在家里修养



来自 MEIZU 20



-------- 原始邮件 --------
发件人：Vitalitypi ***@***.***>
时间：2024年2月17日 18:49
收件人：ZhuoLinLi-shu/TPGCN ***@***.***>
抄送：Subscribed ***@***.***>
主题：[ZhuoLinLi-shu/TPGCN] 代码 (Issue #1)


您好，我看到您的论文已被接收，请问什么时候公开代码呢？
